// angular-client/src/app/core/layout/app-bar/app-bar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'rpt-app-bar',
  templateUrl: './app-bar.component.html',
  styleUrls: ['./app-bar.component.scss']
})
export class AppBarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="app-bar">
  <div class="app-bar__item">
    <img
      src="../../../../../assets/Logo.png"
      alt="reptrack Logo"
      class="app-bar__logo"
    />
  </div>
  <h1 class="app-bar__item app-bar__route">Route-Title</h1>
  <div class="app-bar__item app-bar__actions">
    <button>X</button><button>Y</button>
  </div>
</div>

// client/src/domain/layout/AppBar.tsx
import React, { FunctionComponent, useContext } from 'react';
import MaterialButton from '../../components/MaterialButton';
import { AppContext } from '../../context/AppContext';

import './layout.css';

const AppBar: FunctionComponent = () => {
  const { appState } = useContext(AppContext);

  return (
    <div className='app-bar grid-col-4 indent-h-sm'>
      <div className='app-bar__item'>
        <img src='/images/Logo.png' alt='reptrack-logo' className='app-bar__logo' />
      </div>
      <h1 className='app-bar__item app-bar__route'>{appState.headerName}</h1>
      <div className='app-bar__item app-bar__actions'>
        <MaterialButton icon='notifications_none' />
        <MaterialButton icon='person' />
      </div>
    </div>
  );
};

export default AppBar;
