// angular-client/src/app/core/layout/bottom-nav/bottom-nav.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'rpt-bottom-nav',
  templateUrl: './bottom-nav.component.html',
  styleUrls: ['./bottom-nav.component.scss']
})
export class BottomNavComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<nav class="bottom-nav">
  <ul class="nav-list">
    <a
      class="route"
      routerLink="/"
      routerLinkActive="route--active"
      [routerLinkActiveOptions]="{ exact: true }"
    >
      <li class="nav-list__tab">
        <span class="material-icons">home</span>Home
      </li>
    </a>
    <a class="route" routerLink="/workouts" routerLinkActive="route--active">
      <li class="nav-list__tab">
        <span class="material-icons">fitness_center</span>Workouts
      </li>
    </a>
    <li class="nav-list__tab"></li>
    <a class="route" routerLink="/progress" routerLinkActive="route--active">
      <li class="nav-list__tab">
        <span class="material-icons">trending_up</span>Progress
      </li>
    </a>
    <a class="route" routerLink="/calendar" routerLinkActive="route--active">
      <li class="nav-list__tab">
        <span class="material-icons">date_range</span>Calendar
      </li>
    </a>
  </ul>
</nav>

// react-client (CRA - implementation cancelled)/src/domain/layout/BottomNav.tsx
import React, { FunctionComponent, useContext } from 'react';
import { NavLink } from 'react-router-dom';
import MaterialButton from '../../components/MaterialButton';
import { AppContext } from '../../context/AppContext';

import './layout.css';

const BottomNav: FunctionComponent = () => {
  const { appState, dispatch } = useContext(AppContext);

  const handleMainAction = () => {
    if (appState.mainAction.page === 'WorkoutAssistant') {
      dispatch({ type: 'SET_MAIN_ACTION_STATUS', payload: !appState.mainAction.active });
    }
  };

  return (
    <nav className='bottom-nav'>
      <ul className='nav-list'>
        <NavLink exact to='/' activeClassName='route--active' className='route'>
          <li className='nav-list__tab'>
            <span className='material-icons'>home</span>
            Home
          </li>
        </NavLink>
        <NavLink to='/workouts' activeClassName='route--active' className='route'>
          <li className='nav-list__tab'>
            <span className='material-icons'>fitness_center</span>
            Workouts
          </li>
        </NavLink>
        <li className={`nav-list__tab nav-list__tab--center ${!appState.mainAction.page ? 'nav-list__tab--hide' : ''}`}>
          <div className='nav-list__action'>
            <MaterialButton
              onClick={() => handleMainAction()}
              icon={appState.mainAction.icon}
              disabled={!appState.mainAction.page}
              border
            />
          </div>
        </li>
        <NavLink to='/progress' activeClassName='route--active' className='route'>
          <li className='nav-list__tab'>
            <span className='material-icons'>trending_up</span>
            Progress
          </li>
        </NavLink>
        <NavLink to='/calendar' activeClassName='route--active' className='route'>
          <li className='nav-list__tab'>
            <span className='material-icons'>date_range</span>
            Calendar
          </li>
        </NavLink>
      </ul>
    </nav>
  );
};

export default BottomNav;
