// react-client/src/components/BottomNav/index.tsx
import React, { FunctionComponent } from 'react';
import { NavLink } from 'react-router-dom';

import './bottomNav.css';

const BottomNav: FunctionComponent = () => {
  return (
    <nav className='bottom-nav'>
      <ul className='nav-list'>
        <NavLink exact to='/' activeClassName='route--active' className='route'>
          <li className='nav-list__tab'>
            <i className='material-icons'>home</i>
            Home
          </li>
        </NavLink>
        <NavLink to='/workouts' activeClassName='route--active' className='route'>
          <li className='nav-list__tab'>
            <i className='material-icons'>fitness_center</i>
            Workouts
          </li>
        </NavLink>
        <li className='nav-list__tab nav-list__tab--fab'>
          <div className='fab__outer'>
            <div className='fab__inner'>+</div>
          </div>
        </li>
        <NavLink to='/progress' activeClassName='route--active' className='route'>
          <li className='nav-list__tab'>
            <i className='material-icons'>trending_up</i>
            Progress
          </li>
        </NavLink>
        <NavLink to='/calendar' activeClassName='route--active' className='route'>
          <li className='nav-list__tab'>
            <i className='material-icons'>date_range</i>
            Calendar
          </li>
        </NavLink>
      </ul>
    </nav>
  );
};

export default BottomNav;

// angular-client/src/app/core/layout/bottom-nav/bottom-nav.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'rpt-bottom-nav',
  templateUrl: './bottom-nav.component.html',
  styleUrls: ['./bottom-nav.component.scss']
})
export class BottomNavComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<nav class="bottom-nav">
  <ul class="nav-list">
    <a
      class="route"
      routerLink="/"
      routerLinkActive="route--active"
      [routerLinkActiveOptions]="{ exact: true }"
    >
      <li class="nav-list__tab">
        <span class="material-icons">home</span>Home
      </li>
    </a>
    <a class="route" routerLink="/workouts" routerLinkActive="route--active">
      <li class="nav-list__tab">
        <span class="material-icons">fitness_center</span>Workouts
      </li>
    </a>
    <li class="nav-list__tab"></li>
    <a class="route" routerLink="/progress" routerLinkActive="route--active">
      <li class="nav-list__tab">
        <span class="material-icons">trending_up</span>Progress
      </li>
    </a>
    <a class="route" routerLink="/calendar" routerLinkActive="route--active">
      <li class="nav-list__tab">
        <span class="material-icons">date_range</span>Calendar
      </li>
    </a>
  </ul>
</nav>
